#!/usr/bin/env bash
# Inner half of build-wheel.sh. Do not run directly -- it must execute under
# `uv run --python <ver>`, so that `python` is the *target* interpreter.
#
# Why this matters: _raylet.pyd is compiled by the pyx_library rule in
# BUILD.bazel:161 against @local_config_python//:python_headers. That repo is
# generated by grpc's python_configure (wired up in bazel/ray_deps_build_all.bzl:19),
# which resolves the interpreter from PYTHON_BIN_PATH, falling back to PATH.
# Exporting PYTHON_BIN_PATH explicitly pins the headers to the target Python and
# makes bazel re-fetch the repo rule if you previously built a different version.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$HERE/.." && pwd)"

cd "$ROOT_DIR/python"

# Windows path with forward slashes -- bazel repo rules dislike backslashes.
PYTHON_BIN_PATH="$(python -c 'import sys; print(sys.executable.replace(chr(92), "/"))')"
export PYTHON_BIN_PATH
echo "==> PYTHON_BIN_PATH=$PYTHON_BIN_PATH"
python -VV

# Build the wheel. --no-deps: we only want the artifact, not an install.
python -m pip wheel -v -w dist . --no-deps --use-pep517

# Bundle the MSVC runtime DLLs (msvcp140.dll and friends) into the wheel.
# Output goes to ./wheelhouse so the repaired wheel is never confused with the
# unrepaired one left behind in ./dist.
rm -rf wheelhouse
delvewheel repair -w wheelhouse dist/ray-*.whl

echo "==> repaired wheel:"
ls -l wheelhouse
